# Workflow for checking html, css, js
name: File Lint Workflow

# Trigger event
on: push


# Jobs run by workflow
jobs: 

    # Job 1
    Check-HTML:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16
        - run: npm init -y
        - run: npm install htmlhint -g
        - run: npx htmlhint --version
        - run: npx htmlhint "**/*.html"
    
    # Job 2
    Check-CSS:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 16
        - run: npm init -y
        - run: npm install -g csslint
        - run: npx csslint --version
        - run: npx csslint ./*.css